# YES this configuration is confusing
linters:
  enable:
    - stylecheck
    - errorlint # ensure fmt.Errorf uses %w

linters-settings:
  stylecheck:
    checks: ["all", "-ST1003"]
  errcheck:
    exclude-functions:
      - (*github.com/gin-gonic/gin.Context).AbortWithError