# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'
    
    - name: Install pre-commit deps
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    
    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
